remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

navigation:
  - title: Home
    url: /
  - title: API Documentation
    url: /api/
  - title: Examples
    url: /examples/

toc_parameter:
  sanitize: false
  class: ''
  id: ''
  h_min: 1
  h_max: 6
  ordered: false
  item_class: ''
  submenu_class: ''
  base_url: ''
  anchor_class: ''
  skip_no_ids: false
  strip_par: false
